version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=twitgg
      - POSTGRES_USER=twitgg
      - POSTGRES_PASSWORD=twitgg
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/pgdata/data:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: redis
    image: redis:7-alpine
    hostname: redis
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always
  api:
    build:
      context: ./backend/api
      dockerfile: ./docker.conf/Dockerfile
    container_name: api
    image: api
    volumes:
      - ./backend/api:/api
      - /api/node_modules
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=development
    ports:
      - 9595:9595
    links:
      - postgres:postgres
    depends_on:
      - redis
      - postgres
  
  web:
    build:
      context: ./frontend/web
      dockerfile: ./docker.conf/Dockerfile
    container_name: web
    image: web
    volumes:
      - ./frontend/web:/web
      - /web/node_modules
    environment:
      - TZ=Asia/Seoul
    ports:
      - 3000:3000
    depends_on:
      - api
