FROM node:16-alpine

RUN mkdir /web
WORKDIR /web

COPY . .

# production
COPY .env.production .env

RUN npm install -g pm2
RUN npm ci && npm cache clean --force

RUN chown -R node:node ./*

RUN npm run build

CMD [ "pm2-runtime", "/web/ecosystem.config.js" ]
